services:
  - type: web
    name: facebook-clone-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://cloned-f-render.netlify.app
